#
# CVS: $Id: Makefile,v 1.1.1.1 2008-11-23 08:13:23 madoldman Exp $
#
#################################################################

all: deljunk

deljunk:
	$(CC) -o deljunk deljunk.c -I../../include

clean: /tmp
	-rm -fr *~ *.o *.BAK

# DO NOT DELETE
