<?php
$o = array(
	array('userid', 14),
	array('_noname', 2),
	array('firstlogin', 'int'),
	array('lasthost', 16),
	array('numlogins', 'int'),
	array('numposts', 'int'),
	array('nummedals', 'int'),
	array('flags', 2),
	array('passwd', 14),
	array('username', 40),
	array('ident', 40),
	array('termtype', 16),
	array('reginfo', 64),
	array('userlevel', 'int'),
	array('lastlogin', 'int'),
	array('lastlogout', 'int'),
	array('stay', 'int'),
	array('realname', 40),
	array('address', 80),
	array('email', 68),
	array('nummails', 'int'),
	array('lastjustify', 'int'),
	array('gender', 'char'),
	array('birthyear', 'byte'),
	array('birthmonth', 'byte'),
	array('birthday', 'byte'),
	array('signature', 'int'),
	array('userdefine', 'int'),
	array('notedate', 'int'),
	array('noteline', 'int')
);

